###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"shannu",
    "username":"shannu4466",
    "password": "shannu@123456",
    "gender": "Male",
    "location":"Seecunderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"shannu4466",
    "password": "shannu@123456"
}